### ISSUE TITLE
Don't throw when onblocked isn't implemented

### ISSUE THREAD

**Issue by philipwalton** [dhoulb/shelving-mock-indexeddb#3]
This code is causing unhandled error issues for some of our tests (which pass just fine in the browser):
https://github.com/dhoulb/shelving-mock-indexeddb/blob/master/lib/mock.js#L30

It assumes that developers should always implement `onblocked`, but that's not necessarily the case. This issues explains that in some cases `onblocked` never fires, so it can actually be more fool-proof to use a timeout.
https://github.com/w3c/IndexedDB/issues/223

This also doesn't handle the case where a developer implements `onblocked` but does so via `addEventListener('blocked')`, which is a perfectly valid way to do it.

Seems like ensuring blocked is handled should be up to the tests and not up to the mocking library.

**Comment by dhoulb** [comment]
Hi Philip. I think is one of those fuzzy lines between this being a perfect IndexedDB replica, and a testing/bugfinding tool.

I'll remove it and do a new release, because I think you're absolutely right about it being implemented oddly (as an event).  

But I definitely recommend that all IndexedDB integrations implement _something_ that listens to the `blocked` event — otherwise it's an incredibly subtle bug to track down. (I put it in because I had some race conditions within the mock itself that I kept getting tripped up by.)
